// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web; // Return web configuration instead of throwing an error
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnwI2qJNDW3CVNdf1_NidUMUrYTepqAxg',
    appId: '1:420029681993:web:4c0228b4b3c3efe1d68a98',
    messagingSenderId: '420029681993',
    projectId: 'saborly-397b6',
    authDomain: 'saborly-397b6.firebaseapp.com',
    storageBucket: 'saborly-397b6.firebasestorage.app',
    measurementId: 'G-6EWPX5Z5J9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu3clMHcTEFgq1a5tcrESS705RUK1kYd4',
    appId: '1:420029681993:android:d09494f75ec913d5d68a98',
    messagingSenderId: '420029681993',
    projectId: 'saborly-397b6',
    storageBucket: 'saborly-397b6.firebasestorage.app',
  );

 

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu3clMHcTEFgq1a5tcrESS705RUK1kYd4',
    appId: '1:420029681993:android:d09494f75ec913d5d68a98',
    messagingSenderId: '420029681993',
    projectId: 'saborly-397b6',
    storageBucket: 'saborly-397b6.firebasestorage.app',
    iosBundleId: 'com.saborly.soely',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxqspgpuHxseF2UWfOtLlo6kh5HdFpezc',
    appId: '1:420029681993:ios:96c329d1ed598928d68a98',
    messagingSenderId: '420029681993',
    projectId: 'saborly-397b6',
    storageBucket: 'saborly-397b6.firebasestorage.app',
    iosBundleId: 'com.saborley.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnwI2qJNDW3CVNdf1_NidUMUrYTepqAxg',
    appId: '1:420029681993:web:4c0228b4b3c3efe1d68a98',
    messagingSenderId: '420029681993',
    projectId: 'saborly-397b6',
    authDomain: 'saborly-397b6.firebaseapp.com',
    storageBucket: 'saborly-397b6.firebasestorage.app',
    measurementId: 'G-6EWPX5Z5J9',
  );

}