// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web; // Return web configuration instead of throwing an error
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyB8lm-4t0Ox8OkZODqLgnj_AKYfd8iyIGI",
    authDomain: "saborly.firebaseapp.com",
    projectId: "saborly",
    storageBucket: "saborly.firebasestorage.app",
    messagingSenderId: "361344460853",
    appId: "1:361344460853:web:c680024379e3a4c57c697c",
    measurementId: "G-ZCWJE1NKQB",
  );
 
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRIokAyUDhvVYwhT1crAbS0d0bb3mkw1U',
    appId: '1:361344460853:android:e2b3302fee15cce47c697c',
    messagingSenderId: '361344460853',
    projectId: 'saborly',
    storageBucket: 'saborly.firebasestorage.app',
  );
}