// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web; // Return web configuration instead of throwing an error
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8lm-4t0Ox8OkZODqLgnj_AKYfd8iyIGI',
    appId: '1:361344460853:web:0af229c865dfe6c77c697c',
    messagingSenderId: '361344460853',
    projectId: 'saborly',
    authDomain: 'saborly.firebaseapp.com',
    storageBucket: 'saborly.firebasestorage.app',
    measurementId: 'G-L33VF07B93',
  );

  

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRIokAyUDhvVYwhT1crAbS0d0bb3mkw1U',
    appId: '1:361344460853:android:12d431cf23c7109e7c697c',
    messagingSenderId: '361344460853',
    projectId: 'saborly',
    storageBucket: 'saborly.firebasestorage.app',
  );

 

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcM_iGJlHFw8c9NPaZLaf24MsNfcqctfs',
    appId: '1:361344460853:ios:0dba3748e07688e57c697c',
    messagingSenderId: '361344460853',
    projectId: 'saborly',
    storageBucket: 'saborly.firebasestorage.app',
    iosBundleId: 'com.example.soely',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcM_iGJlHFw8c9NPaZLaf24MsNfcqctfs',
    appId: '1:361344460853:ios:0dba3748e07688e57c697c',
    messagingSenderId: '361344460853',
    projectId: 'saborly',
    storageBucket: 'saborly.firebasestorage.app',
    iosBundleId: 'com.example.soely',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8lm-4t0Ox8OkZODqLgnj_AKYfd8iyIGI',
    appId: '1:361344460853:web:0af229c865dfe6c77c697c',
    messagingSenderId: '361344460853',
    projectId: 'saborly',
    authDomain: 'saborly.firebaseapp.com',
    storageBucket: 'saborly.firebasestorage.app',
    measurementId: 'G-L33VF07B93',
  );

}